### ISSUE TITLE
readthedoc from pyproject.toml

### ISSUE THREAD

**Issue by IaroslavR** [cjolowicz/hypermodern-python#63]
Hi. Thank you for this great " Hypermodern Python" series.  
With setup like this:
```
# pyproject.toml
...
[tool.poetry.dependencies]
# project deps
...
python = "<3.8,>=3.7"
# dev deps
black = { version = "^19.10b0", optional = true }
coverage = {version = "^5.1", optional = true }
...
sphinx-rtd-theme = { version = "^0.4.3", optional = true }
toml = { version = "^0.10.0", optional = true }
typeguard = { version = "^2.7.1", optional = true }

[tool.poetry.extras]
dev = ["black", "coverage", ... "toml", "typeguard"]
docs = ["m2r", "sphinx", "sphinx-autodoc-typehints", "sphinx-rtd-theme", "toml"]
```
```
# readthedocs.yml
version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```
we can  
- read `pyproject.toml` from `docs/conf.py` for metadata
- use `pyproject.toml` "as is" without additional `docs/requirements.txt` file
